spring.application.name=first-project

server.port=8000


#now its our responsibility to create chatClient manually
#spring.ai.chat.client.enabled=false


#api key for open ai
#
#spring.ai.openai.api.key=${OPENAI_API_KEY}
#spring.ai.openai.chat.options.model=gpt-4.1
#spring.ai.openai.chat.options.temperature=0.2


#spring.ai.google.genai.api-key=${GEMINI_API_KEY}
#spring.ai.openai.api-key=${GROQ_API_KEY}

spring.ai.model.chat=ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=codellama:latest
spring.ai.ollama.chat.options.temperature=0.7


#spring.ai.openai.base-url=https://api.groq.com/openai/v1
#spring.ai.openai.api-key=${GROQ_API_KEY}
#spring.ai.openai.chat.options.model=openai/gpt-oss-120b
#spring.ai.openai.chat.options.temperature=0.2

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

#database configuration
spring.datasource.url=jdbc:mariadb://localhost:3308/springai
spring.datasource.username=root
spring.datasource.password=root1234

#spring.datasource.url=jdbc:mariadb://localhost:3308/springai
#spring.datasource.username=root
#spring.datasource.password=root1234
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Ollama embedding model
#spring.ai.ollama.embedding.options.model=nomic-embed-text:latest
#
#spring.ai.vectorstore.mariadb.initialize-schema=true
#spring.ai.vectorstore.mariadb.distance-type=COSINE
#spring.ai.vectorstore.mariadb.dimensions=1536



spring.ai.ollama.embedding.options.model=nomic-embed-text:latest

spring.ai.vectorstore.mariadb.initialize-schema=true
spring.ai.vectorstore.mariadb.distance-type=COSINE
spring.ai.vectorstore.mariadb.dimensions=768







#spring.datasource.url=jdbc:postgresql://localhost:5432/ai_chat_memory
##spring.datasource.url=jdbc:postgresql://192.168.10.25:5432/ArogevaDb
#spring.datasource.username=postgres
#spring.datasource.password=postgres

spring.ai.chat.memory.repository.jdbc.initialize-schema=ALWAYS

#spring.ai.chat.memory.repository.jdbc.schema



#
#
#spring.application.name=first-project
#
#server.port=8091
#
## =========================
## Ollama Chat
## =========================
#
#spring.ai.model.chat=ollama
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=codellama:latest
#spring.ai.ollama.chat.options.temperature=0.7
#
#
## =========================
## Ollama Embeddings
## =========================
#
#spring.ai.ollama.embedding.model=nomic-embed-text:latest
#
#
## =========================
## MariaDB
## =========================
#
#spring.datasource.url=jdbc:mariadb://localhost:3308/springai
#spring.datasource.username=root
#spring.datasource.password=root1234
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#
#
## =========================
## MariaDB Vector Store
## =========================
#
#spring.ai.vectorstore.mariadb.initialize-schema=true
#spring.ai.vectorstore.mariadb.distance-type=COSINE
#spring.ai.vectorstore.mariadb.dimensions=768
#
#
## =========================
## JDBC Chat Memory
## =========================
#
#spring.ai.chat.memory.repository.jdbc.initialize-schema=ALWAYS
#
#
## =========================
## Logging
## =========================
#
#logging.level.org.springframework.ai.chat.client.advisor=DEBUG
